# Generated by Django 4.1.2 on 2022-11-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_followers_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='title',
        ),
        migrations.AddField(
            model_name='userpost',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
