# Generated by Django 4.1.2 on 2022-11-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_description_userpost_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Following',
        ),
    ]
